module.exports = [
    {
        artist: "Chris Tomlin",
        capo: null,
        created_at: "2013-04-11T16:10:32Z",
        data_key: "G",
        id: 1,
        info: null,
        license: null,
        spotify_uri: "spotify:track:40lKptao1hxVqA7fd1OOGp",
        text: "INTRO: \r\nEm C G D \r\n\r\n\r\nVERSE 1:\r\nEm         D           G \r\nWater you turned into wine\r\nEm         D             G \r\nOpened the eyes of the blind\r\n                Am \r\nThere's no one like you\r\n           D \r\nNone like you\r\n\r\nVERSE 2:\r\n\r\nInto the darkness you shine\r\nOut of the ashes we rise\r\nThere's no one like you\r\nNone like you\r\n\r\nCHORUS:\r\nEm   \r\nOur God is greater\r\nC \r\nOur God is stronger\r\nG                       D \r\nGod you are higher than any other\r\nEm \r\nOur God is healer\r\nC \r\nAwesome in power\r\n     G       D \r\nOur God our God\r\n\r\nBRIDGE:\r\nEm                       \r\nAnd if our God is for us\r\nC                            \r\nThen who could ever stop us\r\nG \r\nAnd if our God with us \r\nD \r\nThen what can stand against",
        title: "Our God",
        updated_at: "2013-04-11T16:10:32Z",
        year: null
    },
    {
        artist: "Phil Wickham",
        capo: null,
        created_at: "2013-04-12T19:41:27Z",
        data_key: "G",
        id: 4,
        info: null,
        license: null,
        spotify_uri: "spotify:track:2rb4cO7RczQFSvpjTJ4C2P",
        text: "VERSE 1:\r\nG                      Em \r\nYou are the hand, that catches my fall\r\nD                                    C \r\nYou are the friend, that answers my call\r\nG                Em   \r\nYou are my Day, You are my night\r\nD                               C     D \r\nyou are my love, and all of my life\r\n\r\nCHORUS:\r\n              G      D \r\nYou are the love I need\r\n            Em      C \r\nYou are the air I breathe\r\n            G       D            C \r\nYou are my love my Life always forever\r\n             G       D \r\nI would lay down my life\r\n           Em       C \r\nJust to be on your side\r\n             G      D            C              G \r\nYou are my love my Life always forever always forever\r\n\r\nVERSE 2:\r\nG                      Em \r\nYou are the grace, that covers my sin\r\nD                                    C \r\nYou're everthing, the beginning and and\r\nG                Em   \r\nyou have my soul, my heart and my mind\r\nD                               C     D \r\nyou have my love and all of my life\r\n\r\nBRIDGE:\r\nG    D       Em   C       G    D        C \r\nHalleluijah, Halleluijah, Halleluijah, forever",
        title: "Always Forever",
        updated_at: "2013-04-12T19:41:27Z",
        year: null
    },
    {
        artist: "Chris Tomlin",
        capo: null,
        created_at: "2013-04-13T14:35:18Z",
        data_key: "G",
        id: 7,
        info: "",
        license: null,
        spotify_uri: "spotify:track:0jOSpB2zK2O0SNxj8ZT5lp",
        text: "VERSE:\r\nG\r\nThe splendor of the King\r\n         Em\r\nClothed in majesty\r\n                             \r\nLet all the earth rejoice\r\nC\r\nAll the earth rejoice\r\n G\r\nHe wraps Himself in light\r\n                 Em\r\nAnd darkness tries to hide\r\n         \r\nAnd trembles at his voice\r\n    C\r\nTrembles at his voice\r\n\r\n\r\nCHORUS:\r\n        G\r\nHow great is our God, sing with me\r\n        Em\r\nHow great is our God, all will see\r\n        C              D               G                      \r\nHow great, how great is our God\r\n\r\n\r\nVERSE 2: \r\n\r\nAge to age He stands\r\nAnd time is in His hands    \r\nBeginning and the end\r\nBeginning and the end\r\nThe Godhead, three in one\r\nFather, Spirit, Son\r\nThe Lion and the Lamb\r\nThe Lion and the Lamb\r\n\r\n\r\nBRIDGE:\r\nG\r\nName above all names\r\nEm\r\nWorthy of all praise\r\nC           \r\nMy heart will sing\r\n        D               G \r\nHow great is our God\r\n\r\n\r\nCHORUS 2:\r\n               G        C/G         G\r\nThen sings my soul, my Savior God, to Thee\r\n               Am7                 G\r\nHow great Thou art! How great Thou art\r\n                      C/G             G\r\nThen sings my soul, my Savior God, to Thee\r\n               Am7    C/G            G\r\nHow great Thou art! How great Thou art",
        title: "How Great Is Our God",
        updated_at: "2013-08-18T03:17:17Z",
        year: null
    },
    {
        artist: "Chris Tomlin",
        capo: null,
        created_at: "2013-04-13T14:19:39Z",
        data_key: "E",
        id: 5,
        info: "",
        license: null,
        spotify_uri: "spotify:track:3t4dCm7bHSGzl2xigMaN1Y",
        text: "VERSE 1:\r\n\r\nC#m\r\nThis dry and desert land\r\nA                          E      E\r\nI tell myself keep walking on\r\nC#m\r\nHear something up ahead\r\nA                    E     E\r\nWater falling like a song\r\nC#m\r\nAn ever lasting stream\r\nA                     E\r\nYour river carries me home\r\nE\r\nLet it flow\r\nLet it flow\r\n\r\nVERSE 2:\r\n\r\n_A flood for my soul\r\n_A well that never will run dry\r\nI've rambled on my own\r\nNever believing I would find \r\nAn everlasting stream\r\nYour river carries me home\r\nLet it flow\r\nLet it flow\r\n\r\nCHROSU:\r\n\r\nE\r\nOpen the heavens\r\nE\r\nCome living water\r\n                 A               E\r\n All my fountains are in you\r\n\r\nE\r\nStrong like a river\r\nE\r\nYour love is running through\r\n               A                  E\r\nAll my fountains are in you\r\n\r\nBRIDGE:\r\n\r\nC#m\r\nRain down on us\r\nA                   E      E\r\nRain down on us lord",
        title: "All My Fountains",
        updated_at: "2013-07-28T06:57:41Z",
        year: null
    },
    {
        artist: "Vineyard",
        capo: null,
        created_at: "2013-04-13T14:30:51Z",
        data_key: "E",
        id: 6,
        info: "",
        license: null,
        spotify_uri: "spotify:track:5poyVTTMlPwryEjVKj9iHi",
        text: "VERSE 1:\r\n E           B         C#m\r\nYou are the sovereign \"I _Am\"\r\n     A       B\r\nYour name is holy\r\nE           B             C#m\r\nYou are the pure spotless lamb\r\n     A       B    E  B  C#m A B\r\nYour name is holy\r\n\r\nVERSE 2:\r\nE           B        C#m\r\nYou are the Almighty One\r\n     A       B\r\nYour name is holy\r\nE           B                 C#m\r\nYou are the Christ, God's own Son\r\nA            B       E\r\nYour name is holy\r\n\r\nCHORUS:\r\n        E              A         B\r\nIn Your name, there is mercy for sin\r\n         C#m        A   F#m\r\nThere is safety within\r\n        Bsus B\r\nIn Your holy name\r\n        E              A           B\r\nIn Your name, there is strength to remain\r\n   C#m               A      F#m\r\nTo stand in spite of pain\r\n        Bsus B\r\nIn Your holy name",
        title: "Your Name Is Holy",
        updated_at: "2013-08-02T21:27:34Z",
        year: null
    },
    {
        artist: "Hillsong United",
        capo: null,
        created_at: "2013-04-12T19:37:55Z",
        data_key: "B",
        id: 3,
        info: "",
        license: null,
        spotify_uri: "spotify:track:5GeVZ1HHc9GXBV7qPEP9m0",
        text: "INTRO: B G#m7 F# E\r\n\r\n\r\nVERSE 1:\r\n  B\r\nI lay my life down at your feet\r\nG#m7\r\nYou're the only one I need\r\nF#                                  E\r\nI turn to you and you are always there\r\nB\r\nIn troubled times it's you I seek\r\nG#m7\r\nI put you first thats all i need, \r\nF#                         E\r\nI humble all I am all to you\r\n\r\nCHORUS:\r\nB      F#     \r\nOne Way Jesus\r\nG#m7                 E\r\nYou're the only one that I could live for.\r\nB      F#      \r\nOne Way Jesus\r\nG#m7                 A\r\nYou're the only one that I could live for.\r\n\r\nG#m7   E   G#m7   E\r\n\r\nVERSE 2:\r\nB\r\nYou were always, always there\r\nG#m7\r\nEvery how and everywhere\r\nF#                                   E\r\nYour grace abounds so deeply within me\r\nB\r\nYou will never ever change\r\nG#m7\r\nYesterday today the same\r\nF#                             E\r\nForever til forever meets no end \r\n\r\n\r\nBRIDGE:\r\nB                      F#\r\n     You are the way the truth and the life\r\n   G#m7           E                  G#m7\r\nWe live by faith and not by sight for you\r\n      F#           E\r\nWe're living all for you",
        title: "One Way",
        updated_at: "2013-08-25T15:38:10Z",
        year: null
    },
    {
        artist: "Worth Dying For",
        capo: null,
        created_at: "2013-04-12T19:37:01Z",
        data_key: "C",
        id: 2,
        info: null,
        license: null,
        spotify_uri: "spotify:track:3IorGEQyo57m0d9fRcLUlA",
        text: "VERSE 1:\r\n\r\nAm F C Dm \r\nAll I need in this lifetime is You now\r\nAm F C Dm \r\nWith every breath I\u2019m getting closer to You\r\nAm F C Dm Am \r\nI\u2019m never gonna stop reaching out to You\r\nAm F C Dm \r\nAll I can do is yell out\r\nAm F C Dm \r\nI wanna feel wanna know wanna touch You\r\nAm F C Dm \r\nI\u2019m trusting You with every step I take\r\nAm F C Dm \r\nI throw my life into Your hands\r\nAm F C Dm \r\nKnowing You have the perfect plan\r\n\r\nPRE-CHORUS:\r\n\r\nF C /E F F C /E F F C /E C Am \r\nAnd I\u2019m running,\r\nF C /E F F C /E F F C /E C Am \r\nTo be with You\r\nF C /E F F C /E F F C /E C Am G Gsus G \r\nAnd I\u2019m longing, to see Your face\r\n\r\nCHORUS:\r\n\r\nAm C \r\nI could never let this love die down anymore,\r\nF E /G# \r\n\u2018Cause You\u2019re the only One I\u2019d give my life for\r\nAm C \r\nI could never give my heart away to anyone\r\nF E /G# \r\nI give it all to You my only One\r\n\r\nVERSE 2:\r\n\r\nMore of You, less of me\r\nEvery part of my life I give away\r\nWithout You I\u2019m incomplete\r\nI need You desperately\r\n\r\nBRIDGE:\r\n\r\nF E /G# \r\nWe lift our voice screaming out to this world\r\nAm G /B C \r\n\u2018Cause all we really want is You now\r\nDm \r\nCause You\u2019re the only One who can save us",
        title: "My Only One",
        updated_at: "2013-05-20T18:10:07Z",
        year: null
    },
    {
        artist: "Hillsong United",
        capo: null,
        created_at: "2013-06-07T20:58:21Z",
        data_key: "E",
        id: 11,
        info: null,
        license: null,
        spotify_uri: "spotify:track:5VlojXyAGM1q9ke2ybxrVT",
        text: "INTRO:\r\nC#m  E  F#m  G#m\r\n\r\nVERSE 1:\r\nE                       C#m\r\nI see the King of glory coming down the clouds with fire\r\n                F#m                    G#m       C#m\r\nThe whole earth shakes the whole earth shakes\r\nE                        C#m\r\nI see his love and mercy washing over all our sin\r\n           F#m             B\r\nThe people sing the people sing\r\n\r\nChorus:\r\n    G#m  A\r\nHo--sa--nna\r\n    B   C#m\r\nHo--sa--nna\r\n   A           C#m   B\r\nHosanna in the highest\r\n    G#m  A\r\nHo--sa--nna\r\n    B   C#m\r\nHo--sa--nna\r\n   A           B   C#m\r\nHosanna in the highest\r\n\r\n\r\nVERSE 2:\r\nE                  C#m\r\nI see a generation rising up to take the place\r\n              F#m                 G#m\r\nWith selfless faith with selfless faith\r\nE                    C#m\r\nI see a near revival stirring as we pray and seek\r\n             F#m                B\r\nWe're on our knees we're on our knees\r\n\r\n\r\nBRIDGE:\r\nA                         B\r\nHeal my heart and make it clean\r\nE                      C#m\r\nOpen up my eyes to the things i see\r\nA                        B                C#m\r\nShow me how to love like you, have loved me\r\nA                              B\r\nBreak my heart for what breaks yours\r\nE                        C#m\r\nEverything I am for your kingdom come\r\nA                       B    C#m*\r\nAs i walk from earth in to eternity",
        title: "Hosanna",
        updated_at: "2013-06-07T20:58:21Z",
        year: null
    },
    {
        artist: "Newsboys",
        capo: null,
        created_at: "2014-03-27T20:51:52Z",
        data_key: "D",
        id: 49,
        info: "",
        license: null,
        spotify_uri: "spotify:track:2cOkXHZOloMnMN8mWt70vZ",
        text: "VERSE 1:\r\nD \r\nThrough You the blind will see\r\n\r\nThrough You the mute will sing\r\nG \r\nThrough You the dead will rise\r\n\r\nThrough You all hearts will praise\r\nBm   \r\nThrough You the darkness flees\r\nA \r\nThrough You my heart screams\r\n     D \r\nI am free\r\n\r\n\r\nCHORUS:\r\n         D \r\nAnd I am free to run\r\n     G \r\nI am free to dance\r\n     Bm                            A \r\nI am free to live for you\r\n     D \r\nI am free\r\n\r\nYes, I am free\r\n\r\n\r\nVERSE 2:\r\nD \r\nThrough You the Kingdom comes\r\n\r\nThrough you the battle's won\r\nG \r\nThrough You I'm not afraid\r\n\r\nThrough You the price is paid\r\nBm                           \r\nThrough You there's victory\r\n  A                               D \r\nBecause of You my soul sings I am free\r\n\r\nYes, I am free",
        title: "I Am Free",
        updated_at: "2014-03-27T20:53:05Z",
        year: null
    },
    {
        artist: "Kari Job",
        capo: null,
        created_at: "2013-04-13T14:40:32Z",
        data_key: "G",
        id: 8,
        info: "",
        license: null,
        spotify_uri: "spotify:track:66QSW1IoC9wIONDH6Qe88q",
        text: "VERSE 1:\r\nD              Am\r\n  Worthy is the, Lamb who was slain\r\nC                G\r\n  Holy, Holy, is He\r\nD                 Am\r\n  Sing a new song, to him who sits on\r\nC                 G\r\n  Heaven's mercy seat (2x)\r\n\r\nCHORUS:\r\nD\r\n  Holy, Holy, Holy\r\nAm\r\n  Is the Lord God Almighty\r\nC                             G\r\n  Who was, and is, and is to come\r\nD\r\n  With all creation I sing\r\nAm\r\n  Praise to the King of Kings\r\nC\r\n  You are my everything\r\nG                    D     Am  C  G\r\n  And I will adore You\r\n\r\n\r\nVERSE 2:\r\nD                    Am\r\n Clothed in rainbows, of living color\r\nC                        G\r\n Flashes of lightning, rolls of thunder\r\nD\r\n Blessing and honor, strength and\r\nAm\r\nGlory and power be\r\nC                     G\r\n To You the only wise King\r\n\r\n\r\nVERSE 3:\r\nD                    Am\r\n  Filled with wonder, awestruck wonder\r\nC                         G\r\n  At the mention of your name\r\nD\r\n  Jesus your name is power\r\nAm                      \r\n  Breath, and living water\r\nC                     G\r\n  Such a marvelous mystery",
        title: "Revelation Song",
        updated_at: "2013-09-01T14:14:30Z",
        year: null
    },
    {
        artist: "Kristian Stanfill",
        capo: null,
        created_at: "2013-06-07T20:39:55Z",
        data_key: "G",
        id: 9,
        info: "",
        license: null,
        spotify_uri: "spotify:track:0UriMyD9ek5oKs3va4PqVo",
        text: "VERSE 1:\r\nG\r\nI hear the Savior say\r\n    D                  G\r\nThy strength indeed is small\r\n         Em7                 C\r\nChild of weakness, watch and pray\r\n        G        D      G\r\nFind in Me thine all in all\r\n\r\n\r\nCHORUS:\r\nG             Em7\r\nJesus paid it all\r\nG            D\r\nAll to Him I owe\r\nG                G/B   C2\r\nSin had left a crimson stain\r\n   G         D        G\r\nHe washed it white as snow.\r\n\r\n\r\nVERSE 2:\r\n      G\r\nLord, now indeed I find\r\n    D                G\r\nThy pow\u2019r, and Thine alone\r\n    Em7                 C\r\nCan change the leper\u2019s spots\r\n    G        D        G\r\nAnd melt the heart of stone\r\n\r\n\r\nVERSE 3:\r\n    G                         \r\nAnd when before the throne\r\n  D            G\r\nI stand in Him complete\r\n      Em7             C\r\nJesus died my soul to save\r\n   G          D       G\r\nMy lips shall still repeat\r\n\r\n\r\nBRIDGE:\r\n  G              G/B  C\r\nO praise the One who paid my debt\r\nG/B  Am7            G/B  C\r\nAnd raised this life up from the dead\r\n  G              G/B  C\r\nO praise the One who paid my debt\r\nG/B  Am7            G/B  C\r\nAnd raised this life up from the dead",
        title: "Jesus Paid It All",
        updated_at: "2013-07-28T07:15:04Z",
        year: null
    },
    {
        artist: "Shane & Shane",
        capo: null,
        created_at: "2013-12-03T16:08:50Z",
        data_key: "G",
        id: 43,
        info: "",
        license: null,
        spotify_uri: "spotify:track:1f5AW15GV76mk8JNxaPJIx",
        text: "VERSE 1:\r\nG                                D7            G\r\nSilent Night, Holy Night, all is calm, all is bright\r\nC                       G                       C                  G\r\n'round yon virgin, mother and child, Holy infant so tender and mild\r\nD7                      G                     D7           G\r\nsleep in heavenly  peace, sleep in heavenly  peace\r\n\r\n\r\nVERSE 2:\r\nG                                 D7                      G\r\nSilent Night, Holy Night,  Shepherds quake, At the sight\r\nC                              G                    C                          G\r\nGlories stream from Heaven above,  Heavenly Hosts sing Alleluia\r\nD7                        G     G             D7         G\r\nChrist the Savior is born, Christ the Savior is born\r\n\r\n\r\nVERSE 3:\r\nG                                D7              G \r\nSilent night, Holy night, Son of God, Love's pure light\r\nC                                 G             C                        G\r\nradiant beams from Thy Holy face, with the dawn of re-deeming grace\r\nD7                      G                 D7            G\r\nJesus, Lord at Thy birth, Jesus, Lord at Thy birth",
        title: "Silent Night",
        updated_at: "2013-12-03T16:08:50Z",
        year: null
    },
    {
        artist: "Hillsong",
        capo: null,
        created_at: "2014-03-20T03:54:47Z",
        data_key: "E",
        id: 48,
        info: "",
        license: null,
        spotify_uri: "spotify:track:1urrG04mC0IopJD7vpKiiW",
        text: "INTRO:\r\nC#m  E  F#m  A2\r\n\r\nVERSE 1:\r\nC#m\r\nHere I am\r\n           E\r\nDown on my knees again\r\n             B\r\nSurrendering all\r\n             A2\r\nSurrendering all\r\n\r\n\r\nVERSE 2:\r\nC#m\r\nFind me here\r\n            E\r\nLord as You draw me near\r\n              B\r\nDesperate for You\r\n              A2\r\nDesperate for You\r\n\r\n\r\nCHORUS 1:\r\n  C#m\r\nI surrender\r\n  E           F#m  A\r\nI surrender\r\n\r\n\r\nVERSE 3:\r\nC#m\r\nDrench my soul \r\n             E\r\nAs mercy and grace unfold\r\n             B\r\nI hunger and thirst\r\n             A2\r\nI hunger and thirst\r\n\r\n\r\nVERSE 4:\r\n     C#m\r\nWith arms stretched wide\r\n           E\r\nI know You hear my cry\r\n            B\r\nSpeak to me now\r\n            A2\r\nSpeak to me now\r\n\r\n\r\nCHORUS 2:\r\n  C#m\r\nI surrender\r\n  E\r\nI surrender\r\n          F#m\r\nI want to know You more\r\n          A\r\nI want to know You more\r\n\r\n\r\nINTERLUDE: A2  E  C#m  B  A2  E  B\r\n\r\n\r\nBRIDGE 1:\r\n       A2      E     \r\nLike a rushing wind\r\n      C#m       B\r\nJesus breathe within\r\n               F#m\r\nLord have Your way\r\n               C#m    B\r\nLord have Your way in me\r\n\r\n\r\nBRIDGE 2:\r\n       A2     E\r\nLike a mighty storm\r\n       C#m     B\r\nStir within my soul\r\n               F#m\r\nLord have Your way\r\n               C#m    B\r\nLord have Your way in me",
        title: "I Surrender",
        updated_at: "2014-03-30T16:09:12Z",
        year: null
    },
    {
        artist: "Jesus Culture",
        capo: null,
        created_at: "2013-06-19T19:06:43Z",
        data_key: "E",
        id: 12,
        info: "",
        license: null,
        spotify_uri: "spotify:track:2WSh1Vq9elAti440TjyByV",
        text: "INTRO:\r\nC#m  B  A  B\r\n\r\nVERSE 1:\r\nC#m\r\nHere I am before you\r\nB\r\nFalling in love and seeking your truth\r\nA\r\nKnowing that your perfect grace\r\nB\r\nHas brought me to this place\r\nC#m\r\nBecause of you I freely live\r\nB\r\nMy life to you, oh God, I give\r\nF#m\t\t\tC#m\r\nSo I stand before You God\r\n\tE\t\t\t        B\r\nI lift my voice because you set me free\r\n\r\nCHORUS:\r\n           E\r\nSo I shout out your name\r\n               B\r\nFrom the rooftops I proclaim\r\n\t       C#m                  A  F#m\r\nThat I am Yours, I am yours\r\nE                                      B\r\nAll that I am I place into Your loving hands\r\n         C#m                  A F#m\r\nAnd I am Yours, I am Yours\r\n\r\nVERSE 2:\r\nAll the good You've done for me\r\nI lift up my hand up hand for all to see\r\nYou're the only one \r\nWho brings me to my knees\r\nTo share this love across the earth\r\nThe beauty of Your Holy Word\r\n\r\nSo I stand before You God\r\nI lift my voice because you set me free\r\n\r\nBRIDGE:\r\nE\t\t\t  \r\nHere I am, I stand with arms wide open\r\n\tC#m\t\t\t\tA (F#m)\r\nTo the one, the Son, the everlasting God (2x)",
        title: "Rooftops",
        updated_at: "2013-09-01T14:12:11Z",
        year: null
    },
    {
        artist: "Hillsong United",
        capo: null,
        created_at: "2013-06-19T19:15:58Z",
        data_key: "G",
        id: 15,
        info: null,
        license: null,
        spotify_uri: "spotify:track:7HdvPclBiBpuUzpERTYfxK",
        text: "VERSE 1:\r\nG\r\nYou stood before creation\r\nC\r\neternity in Your hand\r\nG/B                     Em\r\nYou spoke the earth into motion\r\n            C\r\nMy soul now to stand\r\n\r\n\r\nVERSE 2:\r\nG\r\nYou stood before my failure\r\n    C\r\nAnd carried the cross for my shame\r\n   G/B                      Em\r\nMy sin weighed upon Your shoulders\r\n            C\r\nMy soul now to stand\r\n\r\n\r\nPRECHORUS:\r\n                 C\r\nSo what can I say\r\nAm                 Em\r\nAnd what could I do\r\n                    C     D\r\nBut offer this heart O God\r\n        Em      G  D  Em  C  G  D  Em\r\nCompletely to You\r\n\r\n\r\nVERSE 3:\r\n   G\r\nSo I'll walk upon salvation\r\n     C\r\nYour Spirit alive in me\r\n     G/B                  Em\r\nThis life to declare Your promise\r\n            C\r\nMy soul now to stand\r\n\r\n\r\nCHORUS:\r\nC         G\r\nSo I'll stand\r\n     D             Em            C\r\nWith arms high and heart abandoned\r\n   G          D       Em        C\r\nIn awe of the One who gave it all\r\n       G\r\nI'll stand\r\n    D           Em\r\nMy soul Lord to You surrendered\r\nC       G        D  Em\r\nAll I am is Yours",
        title: "The Stand",
        updated_at: "2013-06-19T19:15:58Z",
        year: null
    },
    {
        artist: "Chris Tomlin",
        capo: null,
        created_at: "2013-12-13T16:13:03Z",
        data_key: "G",
        id: 44,
        info: "",
        license: null,
        spotify_uri: "spotify:track:1HF2PdJDpLthHOS3GwOaIn",
        text: "VERSE 1:\r\n G              C\r\nAngels we have heard on high\r\n      G             D\r\nSweetly singing o'er the plains\r\n   G               C\r\nAnd the mountains in reply,\r\n   G                    D\r\nEchoing their joyous strains\r\n\r\n\r\nCHORUS:\r\n  G  Am  G  D\r\nGloria\r\nG           C    D\r\nIn excelsis de o\r\n  G  Am  C  D\r\nGloria\r\nG               C  D  G\r\nIn excelsis deo\r\n\r\n\r\nVERSE 2:\r\nShepherds, why this jubilee\r\nWhy yours joyous strains prolong?\r\nWhat the gladsome tidings be\r\nWhich inspire your heavenly song?\r\n\r\n\r\nVERSE 3:\r\nCome to Bethlehem and see\r\nHim whose birth the angels Sing\r\nCome, adore on bended knee\r\nChrist, the Lord, the newborn King\r\n",
        title: "Angels We Have Heard On High",
        updated_at: "2013-12-13T16:13:03Z",
        year: null
    },
    {
        artist: "David Crowder Band",
        capo: null,
        created_at: "2013-06-19T19:12:57Z",
        data_key: "G",
        id: 14,
        info: "",
        license: null,
        spotify_uri: "spotify:track:6WSFMa721PvfnspCRsGOMh",
        text: "VERSE 1:\r\nG\r\nHe is jealous for me\r\nEm\r\nLoves like a hurricane, I am a tree\r\nD                                          C\r\nBending beneath the weight of his wind and mercy\r\nG\r\nWhen all of a sudden\r\n                      Em\r\nI am unaware of these afflictions eclipsed by glory\r\n      D\r\nAnd I realize just how beautiful You are\r\n        C\r\nAnd how great Your affections are for me\r\n\r\n\r\nPRE CHORUS:\r\n    G                   Em\r\nAnd oh, how He loves us oh\r\n          D\r\nOh how He loves us\r\n                C\r\nHow He loves us so\r\nG   Em\r\n\r\n\r\nCHORUS:\r\nG\r\nHe loves us,\r\n          Em\r\nOh how He loves us\r\n          D\r\nOh how He loves us\r\n          C\r\nOh how He loves.\r\n\r\n\r\nVERSE 2:\r\nG\r\nWe are His portion and He is our prize\r\nEm\r\nDrawn to redemption by the grace in His eyes\r\nD                               C\r\nIf grace is an ocean, we\u2019re all sinking\r\nG\r\nSo Heaven meets earth like an unforeseen kiss\r\nEm\r\nAnd my heart turns violently inside of my chest\r\nD\r\nI don\u2019t have time to maintain these regrets\r\nC\r\nWhen I think about, the way\r\n\r\n\r\nCHORUS:\r\n         G\r\nYeah, He loves us\r\n          Em\r\nOh how He loves us\r\n          D\r\nOh how He loves us\r\n           C\r\nOh how He loves",
        title: "How He Loves",
        updated_at: "2013-09-06T03:33:27Z",
        year: null
    },
    {
        artist: "Kim Walker",
        capo: null,
        created_at: "2014-04-02T01:34:03Z",
        data_key: "G",
        id: 50,
        info: "https://www.youtube.com/watch?v=3Q-yM4QCIek",
        license: null,
        spotify_uri: "spotify:track:11FXFt3aRkkcIspzi6vNDt",
        text: "VERSE 1:\r\nC     Em  G      D      C       Em           G    D \r\nI have found a peace that plows on through the storm \r\nC     Em  G      D      C       Em    G    D \r\nI have found a joy that jumps over sadness \r\nC     Em  G      D       C       Em      G    D \r\nI have found a love that lights up every room \r\nC     Em  G  D        C   Em   G    D \r\nI have found, I found You \r\n\r\n\r\nCHORUS:\r\nC                   D             Em \r\nYou are all I want, You are all I need \r\nC                         D        Em \r\nEverything my heart could hope for \r\nC                       D        Em \r\nWe are longing for, the Glory of the Lord \r\nC                            D     Em \r\nCause we know there\u2019s so much more \r\n\r\n\r\nVERSE 2:\r\nI have found a trust that teaches how to rest \r\nI have found a grace that guides me by the hand \r\nI have found a strength that stands like a mountain \r\nI have found, I found You \r\n\r\n\r\nBRIDGE:\r\n     C     G   Em  C    G   Em \r\nOnly You, fill my soul",
        title: "I Have Found",
        updated_at: "2014-04-02T01:43:19Z",
        year: null
    },
    {
        artist: "Shane and Shane",
        capo: null,
        created_at: "2013-07-07T21:16:20Z",
        data_key: "G",
        id: 17,
        info: "Tutorial: http://www.youtube.com/watch?v=yDNKmFukjUk",
        license: null,
        spotify_uri: "spotify:track:1SNisPZg18TbgMuhUKkmlB",
        text: "VERSE 1:\r\n\r\nEm              C\r\nThe Lord is the Spirit\r\n           D\r\nWhere the Spirit of the Lord is, now\r\n         G\r\nThere is liberty\r\nEm             C\r\nAnd the Spirit lives inside of me\r\n          D\r\nWhere the Spirit of the Lord is, now\r\n         G                 G\r\nThere is liberty, there is liberty,\r\n         G\r\nThere is liberty\r\n\r\n\r\nCHORUS:\r\nC                       G\r\nFor freedom You set me free\r\nC                  G\r\nAnd yes, I am free indeed\r\nEm\r\nYou rewrote my name\r\nC\r\nAnd shackled my shame\r\nAm                          D\r\nYou opened my eyes to see\r\n           Em\r\nI am free\r\n\r\n\r\nVERSE 2:\r\nEm                     C\r\nWhen the spirit of the world\r\n         D\r\nComes to kill me and enslave me I will say\r\n         G\r\nThere is liberty\r\nEm                              C\r\nFor the chains of sin that once entangled me\r\n          D\r\nHave been broken, now I'm singing 'cause I'm free\r\n         G                 G\r\nThere is liberty, there is liberty,\r\n         G\r\nThere is liberty\r\n\r\n\r\nBRIDGE:\r\nEm                                      C\r\nThe storm rolled in. It was dark in the land\r\n              D            Em\r\nAs the Son of Man was crucified\r\nEm                                  C\r\nYou don't take his life. He laid it down\r\n            D                  Em\r\nHe paid the price and shed His blood\r\n\r\nEm                      C\r\nIt is done! The veil is torn\r\n       D            Em\r\nHe has won And I am free\r\n         Em\r\nAnd I am free And I am free\r\n\r\nI am free",
        title: "Liberty",
        updated_at: "2013-07-07T21:16:20Z",
        year: null
    },
    {
        artist: "Matt Redman",
        capo: null,
        created_at: "2014-05-01T19:14:55Z",
        data_key: "D",
        id: 51,
        info: "",
        license: null,
        spotify_uri: "spotify:track:2MobJagQB0dGJoRqI8OT0m",
        text: "CHORUS:\r\n          G          D\r\nBless the Lord, O my soul\r\nA/C#  Bm\r\nO my soul\r\nG             D    Asus4  A\r\nWorship His holy name\r\n          G        Bm\r\nSing like never before\r\nG  A  Bm\r\n0 my soul\r\n     G              A        G/D  D  G/D  D \r\nI'll worship Your holy name\r\n\r\n\r\nVERSE 1:\r\n    G         D           A       Bm\r\nThe sun comes up, it's a new day dawning\r\nG            D            A     Bm\r\nIt's time to sing Your song again\r\nG            D              A           Bm\r\nWhatever may pass, and whatever lies before me\r\nG2         D                Asus4 A  D   Dsus4  D\r\nLet me be singing when the even- ing comes.\r\n\r\n\r\nVERSE 2:\r\n       G       D                A        Bm\r\nYou're rich in love, and You're slow to anger\r\n      G       D               A         Bm\r\nYour name is great, and Your heart is kind\r\n    G        D                A       Bm\r\nFor all Your goodness, I will keep on singing\r\nG2           D              Asus4  A  D    Dsus4  D\r\nTen thousand reasons for my heart to find.\r\n\r\n\r\nVERSE 3:\r\n    G       D           A            Bm\r\nAnd on that day when my strength is failing\r\n    G         D            A         Bm\r\nThe end draws near, and my time has come\r\nG        D                   A        Bm\r\nStill my soul will sing Your praise unending\r\nG2           D                 Asus4  A  D  Dsus4  D\r\nTen thousand years and then forevermore",
        title: "Bless The Lord",
        updated_at: "2014-05-05T20:03:43Z",
        year: null
    },
    {
        artist: "David Crowder",
        capo: null,
        created_at: "2013-07-07T21:20:01Z",
        data_key: "G",
        id: 19,
        info: "",
        license: null,
        spotify_uri: "spotify:track:7AjWblplaFoO99VMLnbgQn",
        text: "INSTRUMENTAL:  G  D  Em  C  (2x)\r\n\r\n\r\nVERSE 1:\r\nG           Em        D           C\r\nYou are more beautiful than anyone ever\r\nG        Em              D                C\r\nEveryday You're The same You never change no cever\r\nG               Em        D               C\r\nAnd how could I ever deny the love of my Saviour\r\nG             Em         D          C\r\nYou are to me everything all I need forever\r\n\r\nPRECHORUS: \r\n D             C\r\n How could you be so good\r\n\r\n\r\nCHORUS: \r\nG     D  Em     C\r\nThere is no one like you\r\nG         D      Em         C\r\nThere has never ever been anyone like you\r\n\r\n\r\nVERSE 2: \r\nG         Em            D             C\r\nEverywhere You are there earth or air surrounding\r\nG           Em           D\r\nI'm not alone the heavens sing along\r\nD                C\r\nMy God You're so astounding\r\nG                Em              D\r\nHow could you be so good to be\r\n           C\r\nEternally, I believe it\r\n\r\n\r\nBRIDGE:\r\nD             C\r\nHow could you be so good to me?\r\nD             C\r\nHow could you be so good to me?\r\nD              C\r\nWere not alone so sing along\r\nD              C             C          C\r\nWere not alone so sing along sing along sing along",
        title: "No One Like You",
        updated_at: "2014-01-03T16:49:58Z",
        year: null
    },
    {
        artist: "Phil Wickham",
        capo: null,
        created_at: "2014-05-24T15:10:57Z",
        data_key: "G",
        id: 55,
        info: "",
        license: null,
        spotify_uri: "spotify:track:5C64H6dEsQ15bS9gp0D3Xr",
        text: "VERSE 1:   \r\nG\r\nWho breaks the power of sin and darkness   \r\nC \r\nWhose love is mighty and so much stronger   \r\nEm                 D                         C \r\nThe King of Glory,  the King above all kings   \r\nG  \r\nWho shakes the whole earth with holy thunder   \r\nC   \r\nWho leaves us breathless in awe and wonder   \r\nEm                 D                         C  then stop\r\nThe King of Glory,  the King above all kings   \r\n\r\n\r\nCHORUS:   \r\n                  G \r\nThis is amazing grace   \r\n                   C  \r\nThis is unfailing love   \r\n                         Em  \r\nThat You would take my place   \r\n                         D  \r\nThat You would bear my cross   \r\n                   G  \r\nYou laid down Your life   \r\n                      C   \r\nThat I would be set free   \r\nEm   \r\nOh, Jesus, I sing for   \r\nD                                G   C   \r\nAll that You've done for me   \r\n\r\n\r\nVERSE 2:\r\nWho brings our chaos back into order\r\nWho makes the orphan a son and daughter\r\nThe King of Glory, the King of Glory\r\nWho rules the nations with truth and justice\r\nShines like the sun in all of its brilliance\r\nThe King of Glory, the King above all kings   \r\n\r\n\r\nBRIDGE:  \r\nG  \r\nWorthy is the Lamb who was slain   \r\nC  \r\nWorthy is the King who conquered the grave   \r\nEm   \r\nWorthy is the Lamb who was slain   \r\nC   \r\nWorthy is the King who conquered the grave",
        title: "This Is Amazing Grace",
        updated_at: "2014-06-04T18:05:57Z",
        year: null
    },
    {
        artist: "Hillsong United",
        capo: null,
        created_at: "2013-07-07T21:17:52Z",
        data_key: "D",
        id: 18,
        info: "",
        license: null,
        spotify_uri: "spotify:track:5Mw9bXG1dLNhbjofkVS2oR",
        text: "Bm   (A/C#)    D      A      G\r\n\r\nVERSE 1:\r\nBm              A/C#       D      \r\nYou call me out upon the waters\r\n           A                       G\r\nThe great unknown where feet may fail\r\nBm                  A/C#     D           \r\nAnd there I find You in the mystery\r\n            A                    G\r\nIn oceans deep   My faith will stand\r\n\r\nCHORUS:\r\nG           D              A  \r\nAnd I will call upon Your name\r\nG            D             A  \r\nAnd keep my eyes above the waves\r\n             G\r\nWhen oceans rise    \r\n              D              A   \r\nMy soul will rest in your embrace\r\n           G         (A)     Bm  (A/C#)  D  A  Em\r\nFor I am Yours  and You are mine\r\n\r\nVERSE 2:\r\nBm                     A/C#    D\r\nYour grace abounds in deepest waters\r\n                A                  G\r\nYour sovereign hand   Will be my guide\r\nBm                      A/C#      D         \r\nWhere feet may fail and fear surrounds me\r\n              A                       G\r\nYou've never failed and you won't start now\r\n\r\nINSTRUMENTAL:   Bm  (A/C#)  D  A  Em   (Bm  G  D  A    Bm  G  D  A)\r\n\r\nBRIDGE:\r\nBm                           G\r\n   Spirit lead me where my trust is without borders     \r\n           D                           A\r\n   Let me walk upon the waters  Wherever You would call me\r\nBm                         G\r\n   Take me deeper than my feet could ever wander\r\n            D                                   A\r\n   And my faith will be made stronger   In the presence of my Saviour      (x3)\r\n\r\nBRIDGE 2:\r\nG                            D\r\n   Spirit lead me where my trust is without borders     \r\n            A                          Em\r\n   Let me walk upon the waters  Wherever You would call me\r\nG                          D\r\n   Take me deeper than my feet could ever wander\r\n            A                                   Em\r\n   And my faith will be made stronger   In the presence of my Saviour\r\n\r\nBRIDGE 3:\r\nBm                 A/C#      D\r\n   Spirit lead me where my trust is without borders     \r\n           A                          Em\r\n   Let me walk upon the waters  Wherever You would call me\r\nBm                 A/C#     D\r\n   Take me deeper than my feet could ever wander\r\n            A                                   Em\r\n   And my faith will be made stronger   In the presence of my Saviour            (x2)",
        title: "Oceans",
        updated_at: "2013-07-09T17:21:04Z",
        year: null
    },
    {
        artist: "Hillsong United",
        capo: null,
        created_at: "2013-09-21T01:34:16Z",
        data_key: "A",
        id: 35,
        info: "",
        license: null,
        spotify_uri: "spotify:track:3RFEvHzmPF0cp0XDeDQC9M",
        text: "INTRO:\r\nF#m  D  A\r\n\r\n\r\nVERSE 1:\r\nA\r\nFound love beyond all reason\r\nA                            F#m\r\nYou gave Your life Your all for me\r\n      D                 A\r\nAnd called me Yours forever\r\nA\r\nCaught in the mercy fallout\r\nA\r\nI found hope found life\r\n          F#m\r\nFound all I need\r\nD                A\r\nYou're all I need\r\n\r\n\r\nPRECHORUS:\r\n        E\r\nThe time has come\r\n   F#m                     D\r\nTo stand for all we believe in\r\n    E\r\nSo I for one am gonna\r\nF#m                  D\r\nGive my praise to You (Jesus)\r\n\r\n\r\nCHORUS:\r\n      A\r\nToday, Today it's all or nothing\r\nF#m\r\nAll the way\r\n                          D\r\nThe praise goes out to You\r\n                                   A\r\nYeah all the praise goes out to You\r\n      A\r\nToday, today I live for one thing\r\n   F#m\r\nTo give You praise\r\n                  D\r\nin everything I do\r\n\r\n\r\nBRIDGE:\r\nF#m\r\nAll we are is Yours\r\nBm\r\nAnd all we're living for\r\n      D\r\nIs all You are\r\n      A         E\r\nIs all that You are Lord",
        title: "The Time Has Come",
        updated_at: "2013-10-27T06:00:13Z",
        year: null
    },
    {
        artist: "Matt Maher",
        capo: null,
        created_at: "2014-05-23T18:32:24Z",
        data_key: "G",
        id: 52,
        info: "",
        license: null,
        spotify_uri: "spotify:track:4EHWldZTas5KUyFtT0rQlY",
        text: "VERSE 1:\r\n             G       C        G\r\nLord, I come, I confess\r\nD/F#     Em       D           C\r\nBowing here I find my rest\r\n               G       C      G\r\nWithout You I fall apart\r\n                   G     D                          C   \r\nYou're the One   that guides my heart\r\n\r\n\r\nCHORUS:\r\n             G               C        G      D/F#\r\nLord, I need You, Oh, I need You\r\nEm     C        G        D\r\nEvery hour I need You\r\n     G/B      C                G/D          C\r\nMy one defense, my righteousness\r\n       G/D             D        G\r\nOh God, how I need You\r\n\r\n\r\nVERSE 2:\r\nWhere sin runs deep Your grace is more\r\nWhere grace is found is where You are\r\nAnd where You are, Lord, I am free\r\nHoliness is Christ in me\r\n\r\n\r\nBRIDGE:\r\nC                G/B        D        Em\r\nTeach my song to rise to You\r\nEm                         G/B             C\r\nWhen temptation comes my way\r\n                     C          G/B          D        Em\r\nAnd when I cannot stand I'll fall on You\r\nC                             D              G\r\nJesus, You're my hope and stay",
        title: "Lord I Need You",
        updated_at: "2014-05-23T18:32:24Z",
        year: null
    },
    {
        artist: "Riley Erin",
        capo: null,
        created_at: "2014-05-24T14:36:07Z",
        data_key: "E",
        id: 53,
        info: "",
        license: null,
        spotify_uri: "spotify:track:0hGVMKTuJC3lwD22OhQPpv",
        text: "VERSE 1:\r\nC#m     A            E   B/D#\r\nLead me further into You to the unknown\r\nC#m    A              E                B/D#\r\nFar beyond what I now see that's where I want to go\r\n  C#m     A    E        C#m        A      Bsus\r\nI abandon everything as deep calls out to deep\r\n\r\n\r\nCHORUS:\r\nC#m                A                    E\r\nI want to be lost, I want to be lost in You\r\nB/D# \r\nOverwhelm me\r\nC#m                A                    E\r\nI want to be lost, I want to be lost in You\r\nB/D#          C#m             A\r\nOverwhelm me, take me higher, take me deeper\r\nE                  B/D#\r\nSeeing Your glory, hearing Your whisper\r\nC#m                A                    E\r\nI want to be lost, I want to be lost in You\r\n\r\n\r\nVERSE 2:\r\nShow Your beauty, show Your strength in this holy place\r\nLet it be like gravity that I can't escape\r\nTill my life has been transformed and\r\nMy Heart is one with Yours\r\n\r\n\r\nBRIDGE:\r\nA                          C#m   E  Bsus\r\nLet the things of earth be swept away\r\nA                  C#m      E  Bsus\r\nDraw me close till only You remain",
        title: "Overwhelm Me",
        updated_at: "2014-05-24T14:36:07Z",
        year: null
    },
    {
        artist: "Bethel",
        capo: null,
        created_at: "2013-11-05T00:56:38Z",
        data_key: "E",
        id: 38,
        info: "",
        license: null,
        spotify_uri: "spotify:track:7HIa49Srx26MopV6nQlijU",
        text: "VERSE 1:\r\n       E                     Esus \r\nWhen I call on Your name You answer\r\n       E                        Esus \r\nWhen I fall You are there by my side\r\n      E                 Esus \r\nYou delivered me out of darkness\r\n       E                   Esus \r\nNow I stand in the hope of new life.\r\n\r\n\r\nPRECHORUS:\r\n   F#m7\r\nBy grace I'm free\r\n        A2 \r\nYou've rescued me\r\n    F#m7        Bsus \r\nNow all I am is Yours\r\n\r\n\r\nCHORUS:\r\nE \r\nI've found a love greater than life itself\r\nA2 \r\nI've found a hope stronger and nothing compares\r\nC#m                               A2 \r\nI once was lost now I'm alive in You\r\n                E    A2    E    A2      \r\nI come alive in You\r\n\r\n\r\nVERSE 2:\r\n          E                    A2 \r\nYou're my God and my firm foundation\r\n      E                          A2 \r\nIt is You whom I'll trust at all times\r\n       E                     A2 \r\nI give glory and praise, adoration\r\n      E                       A2 \r\nTo my Saviour who's seated on high",
        title: "Ive Found a Love",
        updated_at: "2013-11-05T00:58:38Z",
        year: null
    },
    {
        artist: "Tim Hughes",
        capo: null,
        created_at: "2013-07-18T03:52:36Z",
        data_key: "F#",
        id: 24,
        info: "",
        license: null,
        spotify_uri: "spotify:track:2xXLVL5sv6ffgoYbhUlmPR",
        text: "VERSE 1:\r\nF#\r\nThe greatest day in history,\r\nB                                 \r\nDeath is beaten, you have rescued me, \r\nD#m                       B  \r\nSing it out, Jesus is alive\r\nF#\r\nThe empty cross, the empty grave\r\nB \r\nLife eternal, you have won the day\r\nD#m                    B \r\nShout it out, Jesus is alive\r\nC#\r\nHe's alive!\r\n\r\n\r\nCHORUS:\r\nF#          B           D#m \r\nOh, happy day, happy day\r\nC#\r\nYou washed my sin away\r\nF#          B           D#m \r\nOh, happy day, happy day\r\nC#                       F#      B       D#m \r\nI'll never be the same\r\n             C#\r\nForever I am changed\r\n\r\n\r\nVERSE 2:\r\nF#\r\nWhen I stand in that place\r\nB \r\nFree at last, meeting face to face\r\nD#m                          B \r\nI am yours, Jesus you are mine\r\nF#\r\nEndless joy, perfect peace\r\nB \r\nEarthly pain finally will cease\r\nD#m \r\nCelebrate, Jesus is alive\r\nC#\r\nHe's alive!\r\n\r\n\r\nBRIDGE:      \r\nD#m                  A#m \r\nOh, what a glorious day\r\n                B \r\nWhat a glorious way\r\nF#\r\nThat you have saved me\r\nF#                  A#m \r\nOh, what a glorious day\r\n                 F#\r\nWhat a glorious name",
        title: "Happy Day",
        updated_at: "2013-12-03T15:53:52Z",
        year: null
    },
    {
        artist: "Phil Wickham",
        capo: null,
        created_at: "2013-07-18T03:27:09Z",
        data_key: "G",
        id: 22,
        info: "",
        license: null,
        spotify_uri: "spotify:track:6O1WbrSpcFCFwV4AyiLQfH",
        text: "VERSE 1:\r\n      G                   C  D       G\r\nWhen peace like a river attendeth my way,\r\n     Em           Am          D\r\nWhen sorrows like sea billows roll\r\n    G       C              Am           D\r\nWhatever my lot, Thou hast taught me to say,\r\n      G           C    D      G\r\nIt is well, it is well with my soul\r\n\r\n\r\nCHORUS:\r\nD                 \r\nIt is well (It is well)\r\n        G\r\nwith my soul (with my soul)\r\n      C           D            G\r\nIt is well, it is well with my soul\r\n\r\n\r\nVERSE 2:\r\nThough Satan should buffet, though trials should come\r\nLet this blest assurance control\r\nThat Christ has regarded my helpless estate\r\nAnd hath shed His own blood for my soul\r\n\r\n\r\nVERSE 3:\r\nMy sin O, the bliss of this glorious thought\r\nMy sin not in part but the whole\r\nWas nailed to the cross and I bear it no more\r\nPraise the Lord, praise the Lord, O my soul\r\n\r\n\r\nVERSE 4:\r\nAnd, Lord, haste the day when the faith shall be sight\r\nThe clouds be rolled back as a scroll\r\nThe trump shall resound and the Lord shall descend\r\nEven so it is well with my soul",
        title: "It Is Well With My Soul",
        updated_at: "2013-07-20T16:03:39Z",
        year: null
    },
    {
        artist: "Tracy Minor",
        capo: null,
        created_at: "2014-05-24T15:07:35Z",
        data_key: "G",
        id: 54,
        info: "",
        license: null,
        spotify_uri: "spotify:track:1g6bJEo9322LrhUqpkQYwl",
        text: "VERSE 1:\r\nEm\r\nLet this be a sacrifice\r\n C                         G          D/F#\r\nLet me dedicate my life to worship you\r\nEm\r\nWont you let this be a sacrifice\r\n C                         G          D/F#\r\nLet me dedicate my life to worship you\r\n\r\n\r\nCHORUS 1:\r\n                    Em \r\nI'm a lover of your presence\r\n                    C\r\nI'm a lover of your presence\r\n                    G        D/F#\r\nI'm a lover of your presence\r\n\r\n\r\nVERSE 2:\r\nEm                       C\r\nA passions stirring deep inside\r\n                  G          D/F#\r\nYou're all that really satisfies, we worship you\r\n\r\n\r\nCHORUS 2:\r\n                     Em\r\nWe're lovers of your presence\r\n                     C\r\nWe're lovers of your presence\r\n                     G\r\nWe're lovers of your presence\r\n                 D/F#\r\nAnd it's all we wanna be\r\n\r\n\r\nBRIDGE:\r\n       Em\r\nCause I was made for love\r\nC\r\nI was made for love\r\n G                    D/F#\r\nI was made for loving you",
        title: "Lover Of Your Presence",
        updated_at: "2014-05-24T15:07:35Z",
        year: null
    },
    {
        artist: "Brian and Jenn Johnson",
        capo: null,
        created_at: "2013-07-18T03:55:01Z",
        data_key: "D",
        id: 25,
        info: "",
        license: null,
        spotify_uri: "spotify:track:5Vpf2fcPtu7hdHr1ewVfLa",
        text: "VERSE:\r\n       Bm    A  G2          Bm    A  G2 \r\nIn the glory of your presence\r\n       Bm    A  G2  Bm    A  G2 \r\nI find rest for my soul\r\n       Bm    A  G2       Bm    A  G2 \r\nIn the depths of your love\r\n       Bm    A  G2       Bm    A /C#  G2 \r\nI find peace makes me whole\r\n\r\n\r\nCHORUS:\r\nD         A  Em7           G2 \r\nI love I love I love your presence\r\nD         A  Em7           G2 \r\nI love I love I love your presence\r\nD      A     Em7          G2 \r\nI love I love I love you Jesus\r\nD         A  Em7           G2 \r\nI love I love I love your presence",
        title: "I Love Your Presence",
        updated_at: "2013-10-28T23:32:15Z",
        year: null
    },
    {
        artist: "Lincoln Brewster",
        capo: null,
        created_at: "2013-07-18T04:04:34Z",
        data_key: "E",
        id: 27,
        info: "",
        license: null,
        spotify_uri: "spotify:track:58tJOZQL1e88VlNdSsmMXf",
        text: "VERSE 1:\r\nE                 Esus          E        Esus\r\nOh Lord my God in You I put my trust\r\nE                 Esus          E        Esus\r\nOh Lord my God in You I put my hope\r\nE                 Esus          E        Esus\r\nOh Lord my God in You I put my trust\r\nE                 Esus          E\r\nOh Lord my God in You I put my hope\r\n\r\n\r\nCHORUS:\r\nB C#m     A2                E   Esus   E\r\nIn You In You I find my peace\r\nB C#m     A2                E   Esus   E\r\nIn You In You I find my strength\r\nB C#m     A2                  E   Esus   E\r\nIn You I live and move and breathe\r\nB   C#m \r\nLet everything I say and do \r\n   Bsus\r\nBe founded by my faith in You\r\n  A2                     B\r\nI lift up holy hands and sing\r\n                E\r\nLet the praises ring!\r\n\r\n\r\nVERSE 2:\r\nE                 Esus          E        Esus\r\nOh Lord my God to You I give my hands\r\nE                 Esus          E        Esus\r\nOh Lord my God to You I give my feet\r\nE                 Esus          E        Esus\r\nOh Lord my God to You I give my everything\r\nE                 Esus          E\r\nOh Lord my God to You I give my life",
        title: "Let The Praises Ring",
        updated_at: "2013-07-18T04:04:34Z",
        year: null
    },
    {
        artist: "Hillsong United",
        capo: null,
        created_at: "2013-07-18T03:47:20Z",
        data_key: "C",
        id: 23,
        info: "",
        license: null,
        spotify_uri: "spotify:track:3PcIyN4w8oNpcPFv4dNeVy",
        text: "INTRO: F  C  G (3x)\r\n\r\n\r\nVERSE 1:\r\n G          F\r\n_A thousand times I\u2019ve failed\r\n             C          G\r\nStill Your mercy remains\r\n             F\r\nAnd should I stumble again\r\n          C          G\r\nI\u2019m caught in Your grace\r\n     Am\r\nEverlasting\r\n       F                   C          G\r\nYour light will shine when all else fades\r\n        Am\r\nNever ending\r\n     F             C        G  F  C  G  F  C\r\nYour glory goes beyond all fame\r\n\r\n\r\nVERSE 2:\r\nG           F\r\nYour will above all else\r\n      C\r\nMy purpose remains\r\nG          F\r\nThe art of losing myself\r\n       C          G\r\nIn bringing You praise\r\n     Am\r\nEverlasting\r\n       F                   C          G\r\nYour light will shine when all else fades\r\n      Am\r\nNever ending\r\n     F             C        G\r\nYour glory goes beyond all fame\r\n\r\n\r\nCHORUS 1:\r\nF                      C\r\nIn my heart and my soul\r\n                       Am\r\nLord I give You control\r\n                    G\r\nConsume me from the inside out\r\n    F                      Am\r\nLord let justice and praise\r\n                 G\r\nBecome my embrace\r\n                     Dm\r\nTo love You from the inside out (repeat)\r\n\r\n\r\nCHORUS 2:\r\n     Am\r\nEverlasting\r\n       F                   C          G\r\nYour light will shine when all else fades\r\n      Am\r\nNever ending\r\n     F             C        G\r\nYour glory goes beyond all fame\r\n           C           F\r\nAnd the cry of my heart\r\n           G      Am\r\nIs to bring You praise\r\n          F      G\r\nFrom the inside out\r\n            F      G\r\nLord my soul cries out",
        title: "From The Inside Out",
        updated_at: "2013-07-20T16:11:02Z",
        year: null
    },
    {
        artist: "Brian and Jenn Johnson",
        capo: null,
        created_at: "2013-07-24T01:25:51Z",
        data_key: "D",
        id: 30,
        info: "",
        license: null,
        spotify_uri: "spotify:track:1xr1CwyP8owuNx29Pp2gjY",
        text: "VERSE:\r\nD          D/C#     G\r\nYou are my favorite song\r\nD       D/C#         G\r\nKing of love Lord of all\r\nD           D/C#\r\nYou are the reason\r\n    G                 Em\r\nThe reason I am here\r\n                D/F#\r\nYour causing my heart to love\r\n     G               A\r\nEach moment you draw near\r\n\r\nCHORUS:\r\nBm   A/C#  G\r\nI am so undone (3x)\r\n  Em             D/F#\r\nI look into your eyes\r\n    G                 A             D  D/C#  G\r\nAnd see the love that burns for me",
        title: "Undone",
        updated_at: "2013-07-28T07:18:30Z",
        year: null
    },
    {
        artist: "Hillsong",
        capo: null,
        created_at: "2013-07-24T00:03:07Z",
        data_key: "G",
        id: 28,
        info: "",
        license: null,
        spotify_uri: "spotify:track:1aqZ4wT92JwutkhYg6Law5",
        text: "VERSE 1:\r\n  Em            C                    G   D/F#\r\nChrist is my reward and all of my devotion\r\n            Em               C\r\nNow there's nothing in this world \r\n                     G   D/F#\r\nThat could ever satisfy\r\n\r\n\r\nPRECHORUS 1:\r\n         C            D    Em \r\nThrough every trial, my soul will sing\r\n   D/F#     C          Em        D\r\nNo turning back, I've been set free\r\n\r\n\r\nCHORUS: \r\n   G\r\nChrist is enough for me\r\n  Em                 D  C\r\nChrist is enough for me\r\n              D      Em    C\r\nEverything I need is in You\r\n              D\r\nEverything I need\r\n\r\n\r\nVERSE 2:\r\nChrist my all in all\r\nMy joy and my salvation\r\nAnd this hope will never fail\r\nHeaven is our home\r\n\r\n\r\nPRECHORUS 2:\r\nThrough every storm, my soul will sing\r\nJesus is here, to God be the glory \r\n\r\n\r\nBRIDGE: \r\n          G\r\nI have decided to follow Jesus\r\n            C                D\r\nNo turning back, no turning back\r\n          G\r\nI have decided to follow Jesus\r\n            C        D       G\r\nno turning back, no turning back",
        title: "Christ Is Enough",
        updated_at: "2013-08-11T05:22:00Z",
        year: null
    },
    {
        artist: "Kari Job",
        capo: null,
        created_at: "2013-07-24T00:04:43Z",
        data_key: "G",
        id: 29,
        info: "",
        license: null,
        spotify_uri: "spotify:track:6nsxFJ7F7fwbhuHke4PvLO",
        text: "VERSE:\r\nG\r\nNo sweeter name\r\n\r\nThan the Name of Jesus\r\nC                     \r\nNo sweeter name\r\n       Em7  D/F#\r\nHave I ever known\r\nG                                \r\nNo sweeter name\r\n         C              Em7  D\r\nThan the Name of Jesus\r\n\r\n\r\nCHORUS:\r\nG\r\nYou are the life to my heart and my soul\r\nC                           Em7     D/F#\r\nYou are the light to the darkness around me\r\nG\r\nYou are the hope to the hopeless and broken\r\nC                 Em7         D/F#\r\nYou are the only truth and the way\r\n\r\nBRIDGE:\r\nAm7     C   D\r\nJesus, Jesus",
        title: "No Sweeter Name",
        updated_at: "2013-07-28T07:06:41Z",
        year: null
    },
    {
        artist: "",
        capo: null,
        created_at: "2013-11-10T18:50:16Z",
        data_key: "G",
        id: 39,
        info: "",
        license: null,
        spotify_uri: "",
        text: "INTRO: Em   D/F# G \r\n       Em  D/F#  G  C\r\n\r\n\r\nVERSE 1:  \r\n     Em                    D/F#        G\r\nYou wrote a letter and You signed Your name\r\nEm          D/F#       G       C\r\nI read ever word of it page by page\r\n     Em\r\nYou said that You'd be coming\r\n       D/F#   G\r\nComing for me soon\r\nEm    D/F#        C         G\r\nOh my God I'll be ready for You\r\n\r\n\r\nCHORUS:\r\n          C              G\r\nI want to run on greener pastures\r\n          D               Em\r\nI want to dance on higher hills\r\n          C                  G\r\nI want to drink from sweeter waters\r\n       D             Em\r\nIn the misty morning chill\r\n       C               G\r\nAnd my soul is getting restless\r\n        D             Em\r\nFor the place where I belong\r\n        C                G\r\nI can\u2019t wait to join the angels\r\n    D\r\nAnd sing my heaven song\r\n\r\n\r\nVERSE 2:\r\n  Em                    D/F#     G\r\nI hear Your voice and I catch my breath\r\nEm           D/F#        G      C\r\nWell done my child enter in, in rest\r\n   Em       D/F#             G\r\nAs tears of joy roll down my cheek \r\n        Em        D/F#      C       G\r\nOh it\u2019s beautiful beyond my wildest dreams ",
        title: "Heaven Song",
        updated_at: "2013-11-26T21:56:48Z",
        year: null
    },
    {
        artist: "Shane & Shane",
        capo: null,
        created_at: "2013-11-26T21:54:21Z",
        data_key: "G",
        id: 41,
        info: "",
        license: null,
        spotify_uri: "spotify:track:5QotKS3VMdPYBn5ucCbLgB",
        text: "VERSE 1:\r\n   G\r\nO come let us adore him\r\nG (B   A   B  C  B   A)\r\nO come let us adore him\r\n   C2  B   A  G  F#  G  C\r\nO come let us adore him\r\n G  D       G\r\nChrist the Lord\r\n\r\n\r\nVERSE 2:\r\n\r\nFor You alone are worthy\r\nFor You alone are worthy\r\nFor You alone are worthy\r\nChrist the Lord\r\n\r\n\r\nVERSE 3:\r\n\r\nWe'll give you all the glory\r\nWe'll give you all the glory\r\nWe'll give you all the glory\r\nChrist the Lord",
        title: "O Come Let Us Adore Him",
        updated_at: "2013-12-03T15:53:08Z",
        year: null
    },
    {
        artist: "Chris Tomlin",
        capo: null,
        created_at: "2013-08-02T21:06:02Z",
        data_key: "G",
        id: 31,
        info: "",
        license: null,
        spotify_uri: "spotify:track:56SvYdddE1igvBFZn17hRx",
        text: "VERSE 1:\r\nG                 C         G\r\nAmazing grace how sweet the sound\r\n     G                   D\r\nThat saved a wretch like me\r\n  G                  C       G\r\nI once was lost, but now I'm found\r\n    G         D     G\r\nWas blind but now I see\r\n\r\nCHORUS:\r\n              C                  G\r\nMy chains are gone, I've been set free\r\n          C                   G\r\nMy God, My Savior has ransomed me\r\n   G/B    C               Em\r\nAnd like a flood his mercy reigns\r\n         D     C        G\r\nUn-ending love, amazing grace\r\n\r\n\r\nVERSE 2:\r\n\u2019Twas grace that taught my heart to fear\r\nAnd grace my fears relieved\r\nHow precious did that grace appear\r\nThe hour I first believed\r\n\r\nVERSE 3:\r\nThe Lord has promised good to me\r\nHis word my hope secures\r\nHe will my shield and portion be\r\nAs long as life endures\r\n\r\nVERSE 4:\r\nThe earth shall soon dissolve like snow\r\nThe sun forbear to shine\r\nBut God, who call\u2019d me here below\r\nWill be forever mine",
        title: "Amazing Grace - My Chains Are Gone",
        updated_at: "2013-11-06T17:57:04Z",
        year: null
    },
    {
        artist: "Phil Wickham",
        capo: null,
        created_at: "2014-05-24T15:15:29Z",
        data_key: "G",
        id: 56,
        info: "",
        license: null,
        spotify_uri: "spotify:track:4dENQI4jYltLQ67ZOROAsT",
        text: "VERSE 1:\r\nC    G         D         Em\r\nOn a hill Your blood was spilled\r\n     C          G           D\r\nYour brow, Your hands, Your feet\r\n     C         G          D        Em\r\nWith nails and thorns the veil was torn\r\n   C      G       D       C    G D       G\r\nTo make a way for me, You made a way for me.\r\n\r\n\r\nCHORUS:\r\nC G    D  Em      C       G        D\r\nJesus, Savior, my God, my King, my Lord\r\nC G    D  Em       C    D          C  G  D  Em  C  G  D\r\nJesus, Savior, the victory is Yours.\r\n\r\n\r\nVERSE 2:\r\nC           G           D        Em\r\nWrapped and bound, they laid You down \r\n   C       G    D\r\n_A perfect sacrifice \r\n    C        G         D                Em  \r\nBut in three days, the stone was rolled away\r\n   C        D   Em\r\nForever You're alive\r\n   C        D   G\r\nForever You're alive\r\n\r\nINTERLUDE:\r\nG  A  Bm  Bm  A\r\nBm  Bm  C  Bm  Bm  A\r\nG  A  Bm  D  C\r\nBm  C  Bm  A  G\r\n\r\nBRIDGE:\r\nG              D  C\r\nDeath has been beaten \r\n    G              Em  D\r\nThe grave has been conquered\r\nG        D C\r\nJesus is risen\r\nEm        D C\r\nLife ever after",
        title: "The Victory",
        updated_at: "2014-06-04T20:35:46Z",
        year: null
    },
    {
        artist: "David Crowder Band",
        capo: null,
        created_at: "2014-05-24T18:24:55Z",
        data_key: "G",
        id: 57,
        info: "",
        license: null,
        spotify_uri: "spotify:track:2iFqa5oxkAE3eJor4tVE8v",
        text: "VERSE 1:\r\nG\t\t\t   G/F#\t    \t\t   C2\t    \r\nTurn your ear to heaven and hear the noise inside\r\n\tG\t\t\t\t     G/F#\r\nThe sound of angels' awe, the sound of angels' songs\r\nC2\t\t\t\t Am7\t\t\t\t\tC2\r\nAll this for a king, we could join and sing, all to Christ the King\r\n\r\n\r\nPRECHORUS 1:\r\nD\t\t  \t  C2\t\tD\t C2\r\nHow constant, how divine, this song of ours will rise\r\nD\t\t\t  C2\r\nO, how constant, how divine\r\n              D\t\t\t  C2\r\nThis love of ours will rise, will rise\r\n\r\n\r\nCHORUS 1:\r\nG\t\t\tD/F#\t\t   Em7\t\tC2\t  Am7\r\nO Praise Him, O praise Him, He is Holy, He is Holy\r\n\r\n\r\nVERSE 2: \r\nG\t\t\t   G/F#\t    \t\t   C2\t    \r\nTurn your gaze to heaven and raise a joyous noise\r\n\tG\t\t\t\t         G/F#\r\nThe sound of salvation come, the sound of rescued ones\r\nC2\t\t\t\t Am\t\t\t\t   C2\r\nAll this for a king, angels join to sing, all for Christ our King\r\n\r\n\r\nCHORUS 2:\r\nG\t\t\tD/F#\t\t   Em7\t\tC2\t  Am7\r\nO Praise Him, O praise Him, He is Holy, He is Holy\r\nG\t\t\tD/F#\t\t   Em7\t\tC2\t  Am7\r\nO Praise Him, O praise Him, He is Holy, He is Holy\r\n\r\n\r\nPRECHORUS 2:\r\nD\t\t\t   C2   D\t\t   \t     C2\r\nHow infinite and sweet, this love so rescuing\r\nD\t\t\t   C2\tD\t\t\t        C2  \t\t\t\r\nO, how infinitely sweet, this great love that has redeemed \r\n\r\nAs one we sing\r\n\r\n\r\nCHORUS 2:\r\nG\t\t D/F#\t  Em7\t    C2\t  Am7\r\nAllelulia, Allelulia, He is Holy, He is Holy\r\nG\t\t D/F#\t  Em7\t    C2\t  Am7\r\nAllelulia, Allelulia, He is Holy, He is Holy",
        title: "O Praise Him",
        updated_at: "2014-05-24T18:26:04Z",
        year: null
    },
    {
        artist: "Dustin Kensrue",
        capo: null,
        created_at: "2014-06-21T20:41:03Z",
        data_key: "E",
        id: 59,
        info: "",
        license: null,
        spotify_uri: "spotify:track:3HOB0bYiXCtxNPpYS65Fuy",
        text: "VERSE 1:\r\nC#m B E\r\n His appearance was so badly marred\r\n A C#m\r\nHe could not have been recognized\r\nC#m B! E! ! A\r\n So dis\ufb01gured, so beyond all human likeness\r\n C#m \r\nThat we hid our eyes\r\n\r\n\r\nVERSE 2:\r\nC#m B E A\r\n Though he carried all our griefs and bore our sorrows\r\n C#m\r\nWe esteemed him not\r\nC#m B E A\r\n But despised him and considered him af\ufb02icted \r\n C#m B\r\nAnd as one reviled by God\r\n\r\n\r\nCHORUS 1: \r\n A \r\nThough all of us have gone astray\r\n C#m\r\nThough all have turned to their own ways\r\n B         A\r\nThe Lord has laid our wickedness on him\r\n A\r\nHis punishment has brought us peace\r\n C#m\r\nAnd crushed for our iniquities\r\n B  F#m\r\nHe died to save his people from their sin\r\n\r\n\r\nVERSE 3:\r\nHe was stricken, and though pierced for our transgressions\r\nHe did not lash out\r\nBut was silent, like a lamb led to the slaughter\r\nSo he opened not his mouth\r\n\r\n\r\nBRIDGE:\r\n A C#m E B\r\nThe might of Yahweh \r\nA C#m B\r\nStands revealed\r\n A C#m E B\r\nAnd by his wounds we\r\nA C#m B\r\nAll are healed\r\n\r\n\r\nCHORUS 2:\r\n B \r\nHe offered up his soul to death\r\n D#m\r\nHe poured it out till none was left\r\n C#        G#m\r\nHe died but now shall rise and surely see\r\n B\r\nThe many he has righteous made\r\n D#m\r\nAnd satis\ufb01ed, his work surveyed,\r\n C#          G#m\r\nThe man of sorrows ever more shall be\r\n\r\nCHORUS 3:\r\nOn high, exalted, lifted up\r\nThe righteous servant raised above\r\nHis mighty hand shall work the will of God\r\nThe nations all shall hear and see\r\nAstonished at his victory\r\nThe kings of men shall shut their mouths in awe",
        title: "Suffering Servant",
        updated_at: "2014-06-21T20:41:03Z",
        year: null
    },
    {
        artist: "David Crowder Band",
        capo: null,
        created_at: "2013-06-19T19:10:19Z",
        data_key: "C",
        id: 13,
        info: "",
        license: null,
        spotify_uri: "spotify:track:3wxKYVarXfM18xlmy94guN",
        text: "INTRO:  C   G   F\r\n\r\n\r\nVERSE 1:\r\nC            G          F\r\nThe day is brighter here with You\r\nC            G      F\r\nThe night is lighter than its hue\r\nC               G         F\r\nWould lead me to believe\r\nC                G         F\r\nWhich leads me to believe\r\n\r\n\r\nCHORUS:\r\nC                G                    F\r\nYou make everything glorious\r\nC                G                    F\r\nYou make everything glorious\r\nC                G                    F          C      G      F\r\nYou make everything glorious and I am Yours\r\n\r\nWhat does that make me?\r\n\r\n\r\nVERSE 2:\r\nC          G             F\r\nMy eyes are small but they have seen\r\nC          G       F\r\nThe beauty of enormous things\r\nC                G         F\r\nWhich leads me to believe\r\nC                G            F\r\nThere\u2019s light enough to see that\r\n\r\n\r\nBRIDGE:\r\nAm           G/B       C             \r\nFrom glory to glory You are glorious\r\n           G\r\nYou are glorious\r\nF              G/B       C             \r\nFrom glory to glory You are glorious\r\n           G\r\nYou are glorious\r\nF\r\nWhich leads me to believe\r\n\r\nWhy I can believe that\r\n\r\n\r\nOUTRO:\r\nC          G  F     \r\nFrom glory to glory\r\n     C          G  F\r\nFrom glory to glory\r\nC                G     F\r\nYou are glorious, You are glorious\r\nC                G     F\r\nYou are glorious, You are glorious",
        title: "Everything Glorious",
        updated_at: "2013-08-02T21:11:43Z",
        year: null
    },
    {
        artist: "Charlie Hall",
        capo: null,
        created_at: "2013-08-09T03:45:57Z",
        data_key: "G",
        id: 33,
        info: "",
        license: null,
        spotify_uri: "spotify:track:138qGmmHf96ZyvWC9qXLFz",
        text: "INTRO:\r\nG  Gsus\r\n\r\n\r\nVERSE 1:\r\n           G             C/G\r\nO Lord my God, When I in awesome wonder\r\n         G                  D/F#      G\r\nconsider all the Worlds Thy hand hath made\r\n           G                C/G\r\nI see the stars, I hear the rolling thunder\r\n               G            D/F#     G\r\nThy pow'r throughout the universe displayed\r\n\r\n\r\nCHORUS:\r\n               G        C/G         G\r\nThen sings my soul, my Savior God, to Thee\r\n               Am7                 G\r\nHow great Thou art! How great Thou art\r\n                      C/G             G\r\nThen sings my soul, my Savior God, to Thee\r\n               Am7    C/G            G\r\nHow great Thou art! How great Thou art\r\n\r\n\r\nVERSE 2:\r\n            G                  C/G\r\nAnd when I think that God, His Son not sparing\r\n             G                D/F#    G\r\nSent Him to die, I scarce can take it in\r\n               G              C/G\r\nThat on the cross, my burden gladly bearing\r\n             G            D/F#    G\r\nHe bled and died to take away my sin\r\n\r\n\r\nVERSE 3:\r\n                  G                    C/G\r\nWhen Christ shall come, with shouts of acclamation\r\n            G                   D/F#      G\r\nAnd take me home, what joy shall fill my heart\r\n              G             C/G\r\nThen I shall bow in humble adoration\r\n             G                  D/F#       G\r\nAnd there proclaim, My God, how great You are",
        title: "How Great Thou Art",
        updated_at: "2013-08-09T03:45:57Z",
        year: null
    },
    {
        artist: "Jesus Culture",
        capo: null,
        created_at: "2013-06-07T20:47:36Z",
        data_key: "G",
        id: 10,
        info: "",
        license: null,
        spotify_uri: "spotify:track:39bVeSE8K5yBLsxAE8saqU",
        text: "INTRO: C  Em  D  (2x)\r\n\r\nVERSE 1:\r\nEm             C\r\nNothing can separate\r\n G             D\r\neven if i ran away \r\nEm         C       G   D  Dsus\r\nyour love never fails\r\n\r\nEm          C\r\nI know I still make mistakes\r\n     G                           D\r\nBut You have new mercies for me everyday\r\nEm                C        G   D  Dsus   \r\nYour love never fails\r\n\r\n\r\nCHORUS:\r\nC             G                   D  \r\nYou stay the same through the ages\r\nAm                 C\r\nYour love never changes\r\n             G                     \r\nThere maybe pain in the night\r\n    D                Am       C\r\nBut joy comes in the morning\r\n     G              D\r\nAnd when the oceans rage\r\n         Am            C\r\nI don't have to be afraid\r\n          G                  D   \r\nBecause I know that You love me\r\nDsus       D             \r\nYour love never fails    \r\n\r\n\r\nVERSE 2:\r\nEm                           C\r\nThe wind is strong and the water's deep\r\n     G                      D\r\nBut I'm not alone in these open seas\r\n        Em                C    G  D  Dsus\r\nCause Your love never fails\r\nEm            C\r\nThe chasm is far too wide\r\nG                               D\r\nI never thought I'd reach the other side\r\n     Em                C     G  D  Dsus\r\nBut Your love never fails\r\n\r\n\r\nBRIDGE:\r\n           C           Em                    D  Dsus  D\r\nYou make, all things, work together for my good.",
        title: "Your Love Never Fails",
        updated_at: "2013-08-25T15:39:09Z",
        year: null
    },
    {
        artist: "Chris Tomlin",
        capo: null,
        created_at: "2013-06-26T18:40:57Z",
        data_key: "G",
        id: 16,
        info: "",
        license: null,
        spotify_uri: "spotify:track:4qGwoTBvRhJ7YGeoQGytJV",
        text: "VERSE 1:\r\nG         C9\r\nBe still, there is a healer\r\nEm7       C9\r\nHis love is deeper than the sea\r\nG         C9\r\nHis mercy is unfailing\r\nEm7       C9\r\nHis arms, a fortress for the weak\r\n\r\n\r\nPRECHORUS:\r\nG                  C         \r\nLet Faith Arise\r\n            Em     D\r\nLet Faith Arise\r\n\r\n\r\nCHORUS:\r\nG\r\nI lift my hands to believe again\r\nG             C9\r\nYou are my refuge, you are my strength\r\nC9               Em7\r\nAs I pour out my heart\r\n\r\nThese things I remember\r\nEm7      C9\r\nYou are faithful God forever\r\n\r\n\r\nVERSE 2:\r\nG                    C9\r\nBe still, there is a river\r\nEm7                  C9\r\nThat flows from Calvary's Tree\r\nG                    C9\r\nA fountain for the thirsty\r\nEm7                  C9\r\nHis grace, that washes over me\r\n\r\n\r\nBRIDGE:\r\n           G\r\nLet faith arise\r\n           C\r\nLet faith arise\r\n        Em\r\nOpen my eyes\r\n        D\r\nOpen my eyes",
        title: "I Lift My Hands",
        updated_at: "2013-09-01T14:13:53Z",
        year: null
    },
    {
        artist: "All Sons and Daughters",
        capo: null,
        created_at: "2013-10-28T23:37:10Z",
        data_key: "E",
        id: 36,
        info: "",
        license: null,
        spotify_uri: "spotify:track:1GHiW6RszfTlgecWxSSbJS",
        text: "INTRO: E\r\n\r\nVERSE:\r\nE\r\nYou broke my chains of sin and shame\r\n                 A\r\nAnd You covered me with grace\r\nE\r\nAnd You mend my life with Your holy fire\r\n         A\r\nYou cover me with grace\r\n               B                                                A\r\nand You are the hand that reaches out to say\r\n\r\n\r\nCHORUS:\r\n              E\r\nI am set free, oh oh oh oh\r\n              A\r\nI am set free, oh oh oh oh\r\n             C#m                 B          A\r\nIt is for freedom, that I am set free\r\n\r\n\r\nBRIDGE:\r\n        C#m\r\nAnd yes Lord\r\n                 B\r\nWe are grateful for Your grace\r\n           A\r\nAnd for Your love",
        title: "I Am Set Free",
        updated_at: "2013-10-28T23:37:10Z",
        year: null
    },
    {
        artist: "Chris Tomlin",
        capo: null,
        created_at: "2013-08-09T03:41:48Z",
        data_key: "E",
        id: 32,
        info: "",
        license: null,
        spotify_uri: "spotify:track:198MQwd4SASt2PPGbtHu2I",
        text: "INTRO:\r\nE   C#m   B  A   E\r\n\r\n\r\nCHORUS:\r\nE\r\nWe will sing, sing, sing\r\n\r\nAnd make music with the heavens\r\n\t   C#m\r\nWe will sing, sing, sing\r\n\r\nGrateful that You hear us\r\n\t      B\r\nWhen we shout your praise\r\n        A\t\t\t\tE\t\t(E   A   G#)\r\nLift high the name of Jesus\r\n\r\n\r\nVERSE 1:\r\nE\r\nWhat's not to love about You?\r\n\r\nHeaven and earth adore You\r\nC#m\r\nKings and kingdoms bow down\r\n\t\t\t     B\r\nSon of God, You are the One\r\n\t        A\r\nYou are the One we're living for\r\n\r\n\r\nVERSE 2:\r\nE\r\nYou are the love that frees us\r\n\r\nYou are the light that leads us\r\nC#m\r\nLike a fire burning\r\n\t\t\t     B\r\nSon of God, You are the One\r\n\t\tA\r\nYou are the one we're living for",
        title: "Sing Sing Sing",
        updated_at: "2013-11-05T00:52:21Z",
        year: null
    },
    {
        artist: "Hillsong United",
        capo: null,
        created_at: "2013-07-18T03:57:29Z",
        data_key: "B",
        id: 26,
        info: "",
        license: null,
        spotify_uri: "spotify:track:318Oy2gX39KVMbhoSHzB8o",
        text: "INTRO:  B\r\n\r\nVERSE 1:\r\nB    G#m          F#sus     E\r\nGod above all the world in motion\r\nB    G#m         F#sus      E\r\nGod above all my hopes and fears\r\nB        G#m\r\nAnd I don't care\r\n         F#sus        E\r\nWhat the world throws at me now\r\nG#m9      E               B  E  F#  G#m  B  E  F#  G#m\r\nI'm gonna be all right\r\n\r\n\r\nVERSE 2:\r\nB    G#m              F#sus   E\r\nHear the sound of the generations\r\nB     G#m         F#sus    E\r\nMaking loud their freedom song\r\nB      G#m\r\nAll in all\r\n         F#sus        E\r\nThat the world would know Your name\r\nG#m9        E\r\nWe're gonna be all right\r\n\r\n\r\nCHORUS:\r\n        B           E\r\nCause I know my God saved the day\r\n       F#      G#m\r\nAnd I know His word never fails\r\n       B         E               C#m\r\nAnd I know my God made a way for me\r\nE             B\r\nSalvation is here\r\n\r\n\r\nBRIDGE 1:\r\nC#m             G#m\r\nSalvation is here\r\nB                E                     C#m\r\nSalvation is here, and He lives in me\r\n             G#m\r\nSalvation is here\r\nB                  E                    C#m\r\nSalvation that died just to set me free\r\n\r\n\r\nBRIDGE 2:\r\nC#m             G#m\r\nSalvation is here\r\nB                E                     C#m\r\nSalvation is here, and He lives in me\r\n             G#m   B\r\nSalvation is here\r\n               C#m                   E\r\n'Cause You are alive and You live in me\r\n\r\n\r\nBRIDGE 3:\r\n             B\r\nSalvation is here\r\nE                  F#                  G#m\r\nSalvation is here, and He lives in me\r\n             B    E\r\nSalvation is here\r\n               C#m                   E\r\n'Cause You are alive and You live in me",
        title: "Salvation Is Here",
        updated_at: "2013-11-02T20:12:21Z",
        year: null
    },
    {
        artist: "Hillsong",
        capo: null,
        created_at: "2013-09-06T03:30:00Z",
        data_key: "G",
        id: 34,
        info: "",
        license: null,
        spotify_uri: "spotify:track:6pz3CHs6Ka1Tn79f7eXMIs",
        text: "INTRO:\r\nG  C9  Em  C9  \r\n\r\nVERSE 1:\r\n\r\nG\r\nYou hold my every moment\r\n    C9      D      G\r\nYou calm my raging seas\r\nG             D/F#       Em\r\nYou walk with me through fire\r\n    C9          D\r\nAnd heal all my disease\r\n\r\n\r\nPRECHORUS:\r\nAm      C/B  C9\r\nI trust in You\r\nAm      C9   D\r\nI trust in You  \r\n\r\n\r\nCHORUS:\r\nG                   Em\r\nI believe You're my Healer\r\nEm                D     C9\r\nI believe You are all I need\r\nG                   Em\r\nI believe You're my Portion\r\n                           C9         D\r\nI believe You're more than enough for me\r\nEm           D/F#  C9   D  Em  D/F#\r\nJesus You're all I need\r\n\r\n\r\nBRIDGE:\r\nEm      D/F#  G           C9\r\nNothing is impossible for You\r\nEm      D/F#  G           C9\r\nNothing is impossible for You\r\nEm      D/F#  G      C/B  C9\r\nNothing is impossible for You\r\n            Em            D\r\nYou hold my world in Your hands",
        title: "Healer",
        updated_at: "2013-11-02T20:15:45Z",
        year: null
    },
    {
        artist: "Phil Wickham",
        capo: null,
        created_at: "2013-11-05T00:47:51Z",
        data_key: "G",
        id: 37,
        info: "",
        license: null,
        spotify_uri: "spotify:track:4YtVhWZF8oPTLOBTqQyCCl",
        text: "Intro:    \r\nG    C    G    C\r\n\r\n\r\nVERSE 1:   \r\nG    C    Em    D\r\nCome and see His glory\r\nCome just as you are\r\nCome and hear the story \r\nOf His heart\r\nGod so loved His children\r\nHe gave His only Son\r\nThat we might be forgiven,\r\nDeath has been overcome\r\n\r\n\r\nCHORUS:\r\n G              C\r\nHallelujah, Hallelujah\r\n Em                              D       C\r\nYou are the God of our salvation\r\n G\r\nYou have conquered\r\n C\r\nYou have risen\r\n Em                               D       C\r\nYou are the God of our salvation\r\n\r\n\r\nVERSE 2:   \r\nG    C    Em    D\r\nCome you tired and weary\r\nCome just as you are\r\nCome and let His mercy\r\nHeal your heart\r\nFor God so loved His children\r\nThat He gave His only Son\r\nThat we might be forgiven,\r\nDeath has been overcome\r\n\r\n\r\nBRIDGE:\r\n\r\nC        D       Em\r\nHoly, Holy, Holy\r\nG                           C\r\nis the Lord our God\r\nC            D            Em\r\nMighty King of Glory,\r\nG                                D\r\nYou have rescued us",
        title: "God Of Our Salvation",
        updated_at: "2013-11-05T00:47:51Z",
        year: null
    },
    {
        artist: "Paul Baloche",
        capo: null,
        created_at: "2013-07-07T21:28:10Z",
        data_key: "G",
        id: 21,
        info: "",
        license: null,
        spotify_uri: "spotify:track:5FRIQHgAU9loZMOSPV8yXD",
        text: "INTRO: G5\r\n\r\nVERSE 1:\r\n\r\nG5                                     C2\r\nPraise is rising, eyes are turning to You\r\n           G5\r\nWe turn to You\r\n                                            C2\r\nHope is stirring, hearts are yearning for You\r\n            G5\r\nWe long for You\r\n\r\n\r\nPRECHORUS:\r\n                 Dsus\r\n'Cause when we see You\r\n               C               G5\r\nWe find strength to face the day\r\n           Dsus\r\nIn Your Presence all our fears\r\nC             G5           Dsus\r\nAre washed away, washed away \r\n\r\n\r\nCHORUS: \r\n  Gsus  G   Em7  C2\r\nHosanna, hosanna\r\n              G5             Dsus\r\nYou are the God Who saves us\r\n            Em7       C2\r\nWorthy of all our praises\r\n  Gsus  G   Em7  C2\r\nHosanna, hosanna\r\n                 G5       Dsus\r\nCome have Your way among us\r\n                  Em7         C2\r\nWe welcome You here, Lord Jesus \r\n\r\n\r\nVERSE 2:\r\nG5                                     C2\r\nHear the sound of hearts returning to you\r\n           G5\r\nWe turn to you\r\nG5                                       C2\r\nIn your kingdom broken lives are made new\r\n                    G5\r\nYou make all things new",
        title: "Hosanna - Praise Is Rising",
        updated_at: "2013-11-06T17:58:56Z",
        year: null
    },
    {
        artist: "Lincoln Brewster",
        capo: null,
        created_at: "2013-12-03T16:04:55Z",
        data_key: "D",
        id: 42,
        info: "",
        license: null,
        spotify_uri: "spotify:track:0XHnKEt6Tih3TvlRcPuKFe",
        text: "VERSE 1:\r\nD                     G       Bm\r\nJoy to the world, the Lord is come\r\n    G        A        Bm\r\nLet earth receive her King\r\n    G       D      G         D\r\nLet every heart prepare Him room\r\n    Bm                 \r\nAnd Heaven and nature sing\r\n    A                \r\nAnd Heaven and nature sing\r\n    G            Em          A      D\r\nAnd Heaven, and Heaven, and nature sing\r\n\r\n\r\nVERSE 2:\r\nD                     G       Bm\r\nJoy to the Earth, the Savior reigns\r\n    G     A           Bm\r\nLet all their songs employ\r\n      G           D              G           D\r\nWhile fields and floods, rocks, hills and plains\r\n    Bm                 \r\nRepeat the sounding joy\r\n    A                 \r\nRepeat the sounding joy\r\n    G     Em          A      D\r\nRepeat, repeat, the sounding joy\r\n\r\n\r\nVERSE 3:\r\nD                        G        Bm\r\nHe rules the world with truth and grace\r\n    G          A       Bm\r\nAnd makes the nations prove\r\n     G      D       G        D\r\nThe glories of His righteousness\r\n    Bm                 \r\nAnd wonders of His love\r\n    A                 \r\nAnd wonders of His love\r\n    G         Em      A       D\r\nAnd wonders, wonders, of His love.",
        title: "Joy To The World",
        updated_at: "2013-12-03T16:04:55Z",
        year: null
    },
    {
        artist: "Matt Maher",
        capo: null,
        created_at: "2013-11-15T17:32:28Z",
        data_key: "G",
        id: 40,
        info: "",
        license: null,
        spotify_uri: "spotify:track:1sfSQ2d6rTsCSQ2cbBIj8r",
        text: "VERSE 1:\r\nG                  G/B            C2\r\nGreat is your faithfulness oh God\r\nEm           D                  C2\r\nYou wrestle with the sinners heart\r\nG               G/B          C2\r\nYou lead us by still waters and to mercy\r\nEm               D          C2\r\nAnd nothing can keep us apart\r\n\r\n\r\nPRECHORUS:\r\n     Am7       G/B\r\nSo remember your people\r\n  C2         D\r\nRemember your children\r\n Am7        G/B\r\nRemember your promise\r\n  C2\r\nOh God\r\n\r\n\r\nCHORUS 1:\r\n    G             D\r\nYour grace is enough\r\n    Em            C2\r\nYour grace is enough\r\n    G        D          C2\r\nYour grace is enough for me\r\n\r\n\r\nVERSE 2:\r\nG                  G/B         C2\r\nGreat is your love and justice God\r\nEm            D              C2\r\nYou use the weak to lead the strong\r\nG            G/B           C2\r\nYou lead us in the song of your salvation\r\nEm           D           C2\r\nAnd all your people sing along\r\n\r\n\r\nCHORUS 2:\r\n    G        D\r\nYour grace is enough\r\n      Em              C2\r\nHeaven reaching down to us\r\n    G        D        C2\r\nYour grace is enough for me\r\n               G        G/B\r\nGod, I see Your grace is enough\r\n   Em             C2\r\nI'm covered in your love\r\n    G        D          C2\r\nYour grace is enough for me\r\n",
        title: "Your Grace Is Enough",
        updated_at: "2013-11-15T17:32:28Z",
        year: null
    },
    {
        artist: "Phil WIckham",
        capo: null,
        created_at: "2014-01-03T16:45:02Z",
        data_key: "A",
        id: 46,
        info: "",
        license: null,
        spotify_uri: "spotify:track:1LKPVdgI8gOVEL9ogwSxu0",
        text: "VERSE 1:\r\nA2                                  D\r\nI can see You in the light of a new dawn\r\nA2                                    D\r\nI can hear You in the words of a love song\r\nF#m\r\nI know it in my heart\r\nA2              E\r\nI know it in my soul\r\nA2\r\nYou're wonderful\r\n             D\r\nYou're wonderful\r\n\r\n\r\nVERSE 2:\r\nA2                                    D\r\nI can feel You in the breath of a newborn\r\nA2                                      D\r\nI can feel You in the wind and the rainstorm\r\nF#m\r\nI know it in my heart\r\nA2              E\r\nI know it in my soul\r\n\r\n\r\nCHORUS:\r\nA2          F#m\r\nOh, You are wonderful\r\n         E        A2      D\r\nAnd what else can my soul sing?\r\n         A2\r\nAll Your hands have made\r\n     F#m\r\nEverything You've done\r\n      E            A2    D\r\nOh my God, You're wonderful\r\n\r\n\r\nVERSE 3:\r\nA2                                               D\r\nCause You were there when the heavens were fashioned\r\nA2                                    D\r\nYou spoke a word and You set it in motion\r\nF#m\r\nI know it in my heart\r\nA2              E\r\nI know it in my soul\r\n\r\n\r\nBRIDGE:\r\n        D                  F#m\r\nIn the brand new life of a brilliant Spring,\r\n    E              A2\r\nThe promises of a wedding ring\r\n        D              F#m\r\nI could see Your love, see Your heart\r\nE              A2\r\nOh, how wonderful You are\r\n     D                 F#m\r\nIn a mothers touch, a fathers pride\r\n   E                A2\r\nA friend who freely gives his life\r\n        D              F#m\r\nI could see Your love, see Your heart\r\nE\r\nOh, how wonderful",
        title: "Wonderful",
        updated_at: "2014-01-03T16:52:44Z",
        year: null
    },
    {
        artist: "David Crowder Band",
        capo: null,
        created_at: "2013-12-20T18:09:35Z",
        data_key: "B",
        id: 45,
        info: "",
        license: null,
        spotify_uri: "spotify:track:6ugP8DJLR78gxi6FeVpag3",
        text: "VERSE 1:\r\nB             E                      B\r\nO holy night, the stars are brightly shining\r\n                       F#              B\r\nIt is the night of the dear Savior\u2019s birth\r\nB             E                     B\r\nLong lay the world in sin and error pining\r\n           Bbm                         D#m\r\nTill He appeared and the soul felt its worth\r\nF#                B\r\nA thrill of hope, the weary soul rejoices\r\nF#                B\r\nFor yonder breaks a new and glorious morn\r\n\r\n\r\nCHORUS:\r\nG#m          D#m      C#m            G#m\r\nFall on your knees, O hear the angel voices\r\nB       F#   B  E  B    F#              B\r\nO night divine, O night when Christ was born\r\n\r\n\r\nVERSE 2:\r\nTruly He taught us to love one another\r\nHis law is love and His Gospel is peace\r\nChains He shall break for the slave is our brother\r\nAnd in His Name all oppression shall cease\r\nSweet hymns of joy in grateful chorus raise we\r\nLet all within us praise His holy Name\r\n\r\n\r\nCHORUS 2:\r\nG#m           D#m     C#m             G#m\r\nChrist is the Lord! Then ever, ever praise we\r\nB     F#     B  E  B   F#         B\r\nHis power and glory ever more proclaim\r\n\r\n\r\nCHORUS 3:\r\nFall on your knees, O hear the angel voices\r\nO night divine, O night when Christ was born\r\nO night Divine, O night, O night divine",
        title: "Oh Holy Night",
        updated_at: "2013-12-20T21:23:53Z",
        year: null
    },
    {
        artist: "Chris Tomlin",
        capo: null,
        created_at: "2013-07-07T21:24:29Z",
        data_key: "C",
        id: 20,
        info: "",
        license: null,
        spotify_uri: "spotify:track:23hpQH3gde7yxn89rBxksN",
        text: "INTRO: Am   F   C/E   Gsus   G\r\n\r\n\r\nVERSE 1:\r\nAm                  F2\r\nCrown Him with many crowns\r\n    C/E           Gsus\r\nThe Lamb upon His throne\r\n      Am      Am/G     D/F#   G\r\nHark! How the heavenly anthem drowns\r\n    G     D       Gsus\r\nAll music but its own\r\n C/E               F2\r\nAwake, my soul and sing\r\n   D                Gsus   G\r\nOf Him who died for me\r\n    Am       Am/G   F2        C/E\r\nAnd hail Him as thy matchless King\r\n        Dm7  Gsus C\r\nThrough all eternity\r\n\r\n\r\nCHORUS:\r\nF2       C/E\r\nMajesty, Lord of all\r\n    F2              Am       Gsus\r\nLet every throne, before Him fall\r\n    F2\r\nThe King of Kings\r\n  C/E\r\nO come adore\r\n    Dm7     C/E       Gsus     C\r\nOur God who reigns forevermore\r\n\r\n\r\nVERSE 2:\r\nAm                    F2\r\nCrown Him the Lord of life\r\n    C/E                Gsus\r\nWho triumphed o'er the grave\r\n    Am      Am/G    D/F#   G\r\nAnd rose victorious in the strife\r\n    G        D       Gsus\r\nFor those He came to save\r\n    C/E            F2\r\nHis glories now we sing\r\n    D                Gsus   G\r\nWho died and rose on high\r\n    Am    Am/G   F2      C/E\r\nWho died eternal life to bring\r\n    Dm7        Gsus      C\r\nAnd lives that death may die\r\n\r\n\r\nBRIDGE:\r\n    F2      C/E     Gsus\r\nAll hail, Redeemer, hail\r\n    C      C/E      F2\r\nFor He has died for me\r\n    F2         C     Am        Gsus\r\nHis praise and glory shall not fail\r\n       F2   Gsus C\r\nThroughout eternity",
        title: "Crown Him",
        updated_at: "2014-02-07T21:48:55Z",
        year: null
    },
    {
        artist: "Planetshakers",
        capo: null,
        created_at: "2014-05-31T16:02:17Z",
        data_key: "C",
        id: 58,
        info: "Lead tutorial: https://www.youtube.com/watch?v=moacGLU_ud8",
        license: null,
        spotify_uri: "spotify:track:7oDqR0F0NUvNRJLeCdgLfP",
        text: "CHORUS:\r\nC                             G                   Am\r\nThrough You I can do anything, I can do all things\r\n                              F  \r\nCause its you who gives me strength, nothing is impossible\r\nC                            G                         Am\r\nThrough you blind eyes are open, Strongholds are broken\r\n                 F\r\nI am living by faith, nothing is impossible\r\n\r\nInterlude:F C Dm  F x2\r\n\r\n\r\nVERSE: \r\nC             Dm              F\r\nI'm not gonna live by what I see,\r\nAm             G              F\r\nI'm not gonna live by what I feel\r\n\r\n\r\nPRECHORUS:\r\nAm        G                  F\r\nDeep down I, Know that You're here with me\r\nAm          G           Dm    F\r\nI know that, You can do anything\r\n\r\n\r\nBRIDGE:\r\nF           C\r\nI believe, I believe,\r\nDm         F\r\nI believe, I believe in You",
        title: "Nothing Is Impossible",
        updated_at: "2014-06-02T20:11:47Z",
        year: null
    },
    {
        artist: "Brian and Jenn Johnson",
        capo: null,
        created_at: "2014-02-16T00:38:35Z",
        data_key: "G",
        id: 47,
        info: "",
        license: null,
        spotify_uri: "spotify:track:0F9OPDbZVBQbujrEeCYrZA",
        text: "VERSE:\r\nG         D            Em      C2\r\nTaste and see that the Lord is good\r\nG             D            Em      C2\r\nOh, taste and see that the Lord is good to me\r\nG                         D\r\nYou\u2019ve turned my mourning into dancing\r\nEm                  C2\r\nPut off my rags and clothed me with gladness\r\nG            D\r\nI will rise, I will praise you\r\nEm                   C2\r\nI\u2019ll sing and not be silent.\r\n\r\nCHORUS:\r\nG          Em     D                   C\r\nOh Lord my God, I will give thanks to you forever\r\nG  Em             D                   C\r\nOh Lord my God, I will give thanks to you.\r\n\r\nBRIDGE:\r\nD                C\r\nI will live only for You\r\n       D                   C\r\nI will lift these hands up to You\r\n       D        C\r\nI will dance before You\r\n       D                C\r\nI will shout it, I will shout it to You",
        title: "Oh Taste And See",
        updated_at: "2014-02-16T17:43:44Z",
        year: null
    }
];
